### ISSUE TITLE
Article Setting: Keyword Rotation (tags & categories)

### ISSUE THREAD

**Issue by jhyland87** [geekwiki/blog#38]
Currently, Articles can have both `tags` and `categories`, like so:
```yaml
---
title: "Article Title"
categories: [ "Linux", "RHEL" ]
tags: [ "nslookup", "dig", "DNS", "nameserver", "resolv.conf", "networking" ]
---
```
Both of which get displayed at the top of the articles as list items inside of an unordered list. If the categories and/or tags count is greater than set limit for keywords to display, then some of the tags or categories will get truncated.  

It may be useful to create another setting to determine what "mode" to use when creating the keywords to display, something that will allow the authors to determine what to prioritize if they get truncated.
